In [1]:
import pandas as pd
import tensorflow as tf

In [2]:
#loading the csv file
data = pd.read_csv('F:/my files/python files/neural networks/Tensorflow lessons/Dataset/mnist_test.csv')
print(data.head())

   label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  ...    28x19  28x20  \
0      7    0    0    0    0    0    0    0    0    0  ...        0      0   
1      2    0    0    0    0    0    0    0    0    0  ...        0      0   
2      1    0    0    0    0    0    0    0    0    0  ...        0      0   
3      0    0    0    0    0    0    0    0    0    0  ...        0      0   
4      4    0    0    0    0    0    0    0    0    0  ...        0      0   

   28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
0      0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0      0  

[5 rows x 785 columns]


In [3]:
#extracting inputs and targets from file
labels = data['label']
labels = pd.get_dummies(labels, prefix=None)
pixels = data.iloc[:, 1:785]
print(pixels.head())
print(labels.head())
print(type(pixels))
print(type(labels))

   1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  1x10  ...    28x19  28x20  \
0    0    0    0    0    0    0    0    0    0     0  ...        0      0   
1    0    0    0    0    0    0    0    0    0     0  ...        0      0   
2    0    0    0    0    0    0    0    0    0     0  ...        0      0   
3    0    0    0    0    0    0    0    0    0     0  ...        0      0   
4    0    0    0    0    0    0    0    0    0     0  ...        0      0   

   28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
0      0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0      0  

[5 rows x 784 columns]
   0  1  2  3  4  5  6  7  8  9
0  0  0  0  0  0  0  0  1  0  0
1  0  0  1  0  0  0  0  0  0  0
2  0  1  0  0  0  0  0  0  0  0
3  1  0  0  0  0  0  0  0

In [4]:
#converting datatype from pandas to a numpy array
labels = labels.values
pixels = pixels.values
print(type(pixels))
print(type(labels))
print(pixels[:5])
print(labels[:5])

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[[0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]]
[[0 0 0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]]


In [5]:
#creating batches for dataset
class create_dataset:
    
    def __init__(self, x_train, y_train, x_val, y_val):
        self.x_train = x_train
        self.y_train = y_train
        self.x_val = x_val
        self.y_val = y_val
        
    def get_batch(self, batch_size):
        data = self.x_train
        lab = self.y_train
        feat = tf.data.Dataset.from_tensor_slices(data)
        op = tf.data.Dataset.from_tensor_slices(lab)
        tot_data = tf.data.Dataset.zip((feat, op))
        batched_data = tot_data.repeat().batch(batch_size)
        iterator = batched_data.make_initializable_iterator()
        sess = tf.InteractiveSession()
        sess.run(iterator.initializer)
        next_batch = iterator.get_next()
        next_batch = sess.run(next_batch)
        sess.close()
        return next_batch
    
    def val_data(self):
        sess = tf.InteractiveSession()
        data = self.x_val
        lab = self.y_val
        size = len(lab)
        dat = tf.data.Dataset.from_tensor_slices(data)
        labe = tf.data.Dataset.from_tensor_slices(lab)
        tot = tf.data.Dataset.zip((dat, labe))
        tot_data = tot.repeat().batch(size)
        iterator = tot_data.make_initializable_iterator()
        sess.run(iterator.initializer)
        val_data = iterator.get_next()
        val_data = sess.run(val_data)
        sess.close()
        return val_data
        
        


In [7]:
val_size = 4000
tot_size = len(data)
siz = tot_size-val_size
x_tr = pixels[:siz]
x_vl = pixels[siz:]
y_tr = labels[:siz]
y_vl = labels[siz:]
mnist = create_dataset(x_tr, y_tr, x_vl, y_vl)
train_x, train_y = mnist.get_batch(50)
val_x, val_y = mnist.val_data()

In [9]:
print(train_x.shape)
print(train_y.shape)
print(val_x.shape)
print(val_y.shape)

(50, 784)
(50, 10)
(4000, 784)
(4000, 10)


The above code snippets gives a detailed insight into how can one create his/her own dataset in tensorflow when you are provided with csv type dataset. First we extract
the data from file using pandas then convert it into numpy array. After that we perform create a class to help us creating batches of dataset and validation set. 